[build-system]
requires = ["setuptools>=48", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
exclude = '''
/(
    \.eggs
  | \.git
  | \.env
  | \.venv
  | _build
  | build
  | dist
)/
'''
